### ISSUE TITLE
Changesets plus localisés

### ISSUE THREAD

**Issue by cquest** [Marcussacapuces91/Check-OSM#2]
Peux-tu limiter à des zones géographiques plus réduites les changesets créés par le bot ?

Pour la mise à jour des populations des communes, je l'ai fait par département pour éviter ça.

**Comment by Marcussacapuces91** [comment]
Par région administrative peut-être ? Sachant que je valide chaque changset manuellement, ça va faire une centaine sur les départements et moins de 10 sur les régions.

L'idée ici est que le robot tourne régulièrement pour corriger automatiquement les nouvelles erreurs dès qu'elles sont faites.

**Comment by Marcussacapuces91** [comment]
J'ai mis en place des layer (JOSM) par région et donc la possibilité de sauvegarder chaque layer dans un changset différent.

C'est en place depuis https://github.com/Marcussacapuces91/Check-OSM/commit/d67d164df241d9bf70056a65d750cb82cdca2bf5
